### PR TITLE
Change from const to var

### PR DESCRIPTION
**Pull request by rajsite**
Using the library with Chromium 40 which does not support the const keyword in strict mode but does support Promise. Saw a previous pull request to make the library more es5 compatible so this seems like the right direction.

### CODE REVIEW

**Review by jahredhope — APPROVED** [review]
Makes sense to me.
Thanks for adding the explanation.

**Comment by rajsite** [comment]
Thanks for taking a look! Is there anything else needed to merge and release?

**Comment by jahredhope** [comment]
Nothing was needed from yourself, just needed to check things on my end.

This change was released with:
https://github.com/jahredhope/promise-file-reader/releases/tag/v1.0.1

Thanks for the improvement and if this new version doesn't solve your problem do get in touch.

**Comment by rajsite** [comment]
Thanks!

**Pull request merged**
